version: '3.4'
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - ${DB_CONTAINER:-db}
    environment:
      - SEED_DB
  db:
    container_name: ${DB_CONTAINER:-db}
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_PORT:-3306}:${MYSQL_PORT:-3306}
    volumes:
      - db-vol:/var/lib/mysql
    env_file: .env
volumes:
  db-vol: