version: '3.3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-vol:/var/lib/mysql
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'spc'
volumes:
  db-vol: